package signals

const ESC     = "\033"
const ESC_INP = "\x1b" 
// const ESC_HEX = "\0x1B"

const (
    ALT_SCR_BUFF_ENABLE =         ESC + "[?1049h"  //Suspends primary buffer and scrollback history. Allocates and displays a blank grid matching current terminal dimensions
    ALT_SCR_BUFF_DISABLE =        ESC + "[?1049l"  //Deallocates alternate buffer. Restores primary buffer visual state and previous cursor coordinates
    X11_MOUSE_REPORTING_ENABLE =  ESC + "[?1000h"  //Terminal emulator ceases native mouse event processing. Transmit mouse click grid coordinates to application stdin
    X11_MOUSE_REPORTING_DISABLE = ESC + "[?1000l"  //Disable
    URXVT_MOUSE_MODE_ENABLE =     ESC + "[?1015h"  //Alters byte encoding for mouse coordinates to support grid dimensions exceeding 223 rows or columns
    URXVT_MOUSE_MODE_DISABLE =    ESC + "[?1015l"  //Disable encoding
    SHOW_CURSOR =                 ESC + "[?25h"    //Renders terminal cursor at its current position
    HIDE_CURSOR =                 ESC + "[?25l"    //Stops rendering cursor
    RESET_MARGINS =               ESC + "[r"       //Removes scrolling restrictions. Resets margins to row1 and max terminal row
    MOV_CURSOR_DOWN =             ESC + "D"        //Moves cursor down 1 row. at bottom margin, shift all rows up. Top row is discarded. Bottom row is left blank
    MOV_CURSOR_UP =               ESC + "M"        //Moves cursor up 1 row. at top margin, shift all rows down. Bottom row is discarded. Top row is left blank
    LINE_INS =                    ESC + "[L"       //Insert a new rowat current cursor position
    LINE_DEL =                    ESC + "[M"       //Delete line
    ERASE_IN_DISPLAY =            ESC + "[2J"      //Clears all character data from the active terminal grid. Cursor coordinate remains unchanged
    ERASE_IN_LINE =               ESC + "[K"       //Clears character data from the current cursor coordinate to the end of the line
    CURSOR_UP =                   ESC + "[A"       //Moves the cursor up by lines without changing columns. 
    CURSOR_DOWN =                 ESC + "[B"       //Moves the cursor down by lines without changing columns. 
    CURSOR_FORWARD =              ESC + "[C"       //Moves the cursor to the right by columns. 
    CURSOR_BACKWARD =             ESC + "[D"       //Moves the cursor to the left by columns. 
    CURSOR_NEXT_LINE =            ESC + "[E"       //Moves the cursor to the beginning of the line lines down. 
    CURSOR_PREVIOUS_LINE =        ESC + "[F"       //Moves the cursor to the beginning of the line lines up. 
    CURSOR_HOME =                 ESC + "[H"       //Moves the cursor to the top-left origin position. 
    // CURSOR_POSITION =          ESC + "[; H ; L  //Moves the cursor to the absolute row and column within the viewport. 
    HORIZONTAL_ABSOLUTE =         ESC + "[G"       //Moves the cursor to the th column horizontally on the current line. 
    VERTICAL_ABSOLUTE =           ESC + "[d"       //Moves the cursor to the th row vertically in the current column. 
    SAVE_CURSOR_POSITION =        ESC + "[s"       //Saves the current cursor coordinates to memory. 
    RESTORE_CURSOR_POSITION =     ESC + "[u"       //Restores the cursor to the most recently saved coordinates. 
    DEVICE_STATUS_REPORT =        ESC + "[6n"      //Requests the terminal to report current cursor coordinates via standard input. 
    //TEXT_CURSOR_BLINKING =      ESC + "[? 12h/l" //Starts (h) or stops (l) the blinking of the terminal cursor. 
    //TEXT_CURSOR_VISIBILITY =    ESC + "[? 25h/l" //Shows (h) or hides (l) the terminal cursor graphic. 
    //SET_CURSOR_SHAPE =          ESC + "[<0-6>SPq"//Modifies the cursor appearance to a block, underline, or vertical bar. 
    ERASE_DOWN =                  ESC + "[0J"      //Clears all text from the current cursor coordinate to the end of the screen. 
    ERASE_UP =                    ESC + "[1J"      //Clears all text from the cursor coordinate to the top of the screen. 
    ERASE_SCREEN =                ESC + "[2J"      //Clears the entire visible display grid. 
    ERASE_SAVED_LINES =           ESC + "[3J"      //Clears the terminal emulator's scrollback history. 
    ERASE_END_OF_LINE =           ESC + "[0K"      //Clears character data from the cursor to the end of the current row. 
    ERASE_START_OF_LINE =         ESC + "[1K"      //Clears character data from the start of the current row up to the cursor. 
    ERASE_ENTIRE_LINE =           ESC + "[2K"      //Clears the entire current row without moving the cursor. 
    INSERT_CHARACTER =            ESC + "[@"       //Inserts blank spaces, shifting existing row text to the right. 
    DELETE_CHARACTER =            ESC + "[P"       //Deletes characters, pulling the remaining row text to the left. 
    ERASE_CHARACTER =             ESC + "[X"       //Overwrites characters with spaces without shifting adjacent text. 
    INSERT_LINE =                 ESC + "[L"       //Inserts blank lines, shifting the current and subsequent rows downwards. 
    DELETE_LINE =                 ESC + "[M"       //Deletes lines, pulling all subsequent rows upwards. 
    //SET_MARGINS =               ESC + "[; r"     //Restricts vertical scrolling operations to a specific row range. 
    // RESET_MARGINS =               ESC + "[r"       //Re-enables scrolling for the full height of the terminal display. 
    REVERSE_INDEX =               ESC + "M"        //Moves cursor up one line, shifting viewport text down if at the top margin. 
    INDEX =                       ESC + "D"        //Moves cursor down one line, shifting viewport text up if at the bottom margin. 
    SCROLL_UP =                   ESC + "[S"       //Scrolls the active text viewport upwards by lines. 
    SCROLL_DOWN =                 ESC + "[T"       //Scrolls the active text viewport downwards by lines. 
    RESET_ATTRIBUTES =            ESC + "[0m"      //Turns off all text styling and color modifications. 
    BOLD =                        ESC + "[1m"      //Applies a bold font weight or increased text intensity. 
    DIM =                         ESC + "[2m"      //Decreases text intensity. 
    ITALIC =                      ESC + "[3m"      //Applies italicized font styling. 
    UNDERLINE =                   ESC + "[4m"      //Renders a line underneath the text characters. 
    SLOW_BLINK =                  ESC + "[5m"      //Causes the text to flash continuously at less than 150 times per minute. 
    RAPID_BLINK =                 ESC + "[6m"      //Causes the text to flash rapidly at more than 150 times per minute. 
    REVERSE_VIDEO =               ESC + "[7m"      //Inverts the foreground and background colors. 
    HIDE_TEXT =                   ESC + "[8m"      //Renders the text invisible. 
    STRIKETHROUGH =               ESC + "[9m"      //Renders a line through the center of the text characters. 
    DOUBLE_UNDERLINE =            ESC + "[21m"     //Applies a double underline or resets bold depending on the emulator. 
    NORMAL_INTENSITY =            ESC + "[22m"     //Disables bold and dim styling effects. 
    NOT_ITALIC =                  ESC + "[23m"     //Disables italic styling effects. 
    NOT_UNDERLINED =              ESC + "[24m"     //Disables single and double underline effects. 
    NOT_BLINKING =                ESC + "[25m"     //Disables text blinking effects. 
    NOT_REVERSED =                ESC + "[27m"     //Disables color inversion effects. 
    REVEAL_TEXT =                 ESC + "[28m"     //Disables the hidden/concealed attribute. 
    NOT_STRIKETHROUGH =           ESC + "[29m"     //Disables strikethrough styling. 
    STANDARD_FOREGROUND =         ESC + "[30-37m"  //Sets the primary text color (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White). 
    //256_FOREGROUND_COLOR = ESC + "[38 ; 5 ;m"    //Sets a specific 8-bit foreground color via code . 
    //RGB_FOREGROUND_COLOR = ESC + "[38 ; 2 ; ; ;m"//Sets a 24-bit true-color foreground using standard RGB values. 
    DEFAULT_FOREGROUND =          ESC + "[39m"     //Restores the terminal emulator's default text color. 
    STANDARD_BACKGROUND =         ESC + "[40-47m"  //Sets the primary background color. 
   // 256_BACKGROUND_COLOR = ESC + "[48 ; 5 ;m"    //Sets a specific 8-bit background color via code . 
   // RGB_BACKGROUND_COLOR = ESC + "[48 ; 2 ; ; ;m"//Sets a 24-bit true-color background using standard RGB values. 
    DEFAULT_BACKGROUND =          ESC + "[49m"     //Restores the terminal emulator's default background color. 
    RESET_DEVICE =                ESC + "c"        //Clears buffers and restores the terminal to initial power-on state. 
   // SET_DISPLAY_COLUMNS = ESC + "[?3h/l"         //Configures the terminal interface width to 132 columns (h) or 80 columns (l). 
   // SET_SCROLLING_MODE = ESC + "[?4h/l"          //Toggles between smooth scrolling (h) or jump scrolling (l). 
   // SET_SCREEN_VIDEO = ESC + "[?5h/l"            //Toggles between global reverse video (h) or standard normal video (l). 
   // SET_LINE_WRAP = ESC + "[?7h/l"               //Enables auto-wrapping text at the edge (h) or disables it (l), causing right-side clipping. 
   // SET_GRAPHICS_MODE = ESC + "[=h/l"            //Adjusts legacy display dimensions and types (e.g., 0=40x25 text, 19=320x200 graphics). 
   
   UP_ARROW_INPUT =               ESC_INP + "[A"
   DOWN_ARROW_INPUT =             ESC_INP + "[B"
   LEFT_ARROW_INPUT =             ESC_INP + "[D"
   RIGHT_ARROW_INPUT =            ESC_INP + "[C"
   DEL_INPUT =                    ESC_INP + "[3~"
   HOME_INPUT =                   ESC_INP + "[H"
   END_INPUT =                    ESC_INP + "[F"
   
)
